# Generated by Django 2.2 on 2023-03-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0002_auto_20230305_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='hoby_image',
            field=models.CharField(default='https://fjwp.s3.amazonaws.com/blog/wp-content/uploads/2020/02/29113959/hobby-money.png', max_length=500),
        ),
    ]
