# Generated by Django 2.2 on 2023-03-17 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0003_hobby_hoby_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hobby',
            old_name='hoby_image',
            new_name='hobby_image',
        ),
    ]
